spring:
  application:
    name: TransContBot

mail:
  host: imap.mail.ru
  username: batukhtin.v@delotech.ru
  password: Mdh7p7pEwrE8kcLx4hYx
  folder: 1 линия заявки
  interval-seconds: 60

bot:
  name: TkServiceBot
  token: 7918392630:AAHExIzFNCzc_LoJAbXWT1_Zd6NUEh87WM0
  group: -1002551515752
